## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
dist: trusty
sudo: true
addons:
    apt:
        packages:
            - xorg-dev
            - cmake 
            - libxrandr-dev 
            - libxinerama-dev 
            - libxcursor-dev 
            - mesa-utils
            - libosmesa6
            - libosmesa6-dev
            - xvfb

julia:
  - 1.0
  - nightly
notifications:
  email: false

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly

before_install: # homebrew for mac
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +extension RENDER"; fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.add("MAT"); Pkg.build("PopulationDynamics"); Pkg.test("PopulationDynamics"; coverage=true)'
after_success:
  # push coverage results to Coveralls
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
