## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
dist: trusty
sudo: true
addons:
    apt:
        packages:
            - xorg-dev
            - cmake 
            - libxrandr-dev 
            - libxinerama-dev 
            - libxcursor-dev 
            - mesa-utils

julia:
  - 1.0
  - nightly
notifications:
  email: false

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly

before_script: # homebrew for mac
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.add("MAT"); Pkg.build("PopulationDynamics"); Pkg.test("PopulationDynamics"; coverage=true)'
after_success:
  # push coverage results to Coveralls
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
